# Generated by Django 5.1.7 on 2025-03-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('kunden_nr', models.AutoField(primary_key=True, serialize=False)),
                ('firma', models.CharField(max_length=60)),
                ('anschrift', models.CharField(max_length=60)),
                ('telefon_nr', models.CharField(blank=True, max_length=20)),
                ('fax_nr', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('stadt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vermerk',
            fields=[
                ('gespraechs_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField(auto_now_add=True)),
                ('uhrzeit', models.TimeField(auto_now_add=True)),
                ('kontaktart', models.CharField(choices=[('Anruf', 'Anruf'), ('Besuch', 'Besuch')], default='Anruf', max_length=6)),
                ('anrede', models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Divers', 'Divers')], default='Herr', max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('firma', models.CharField(max_length=60)),
                ('anschrift', models.CharField(max_length=60)),
                ('telefon_nr', models.CharField(blank=True, max_length=20)),
                ('fax_nr', models.CharField(blank=True, max_length=20)),
                ('betreff', models.CharField(max_length=40)),
                ('wunsch', models.CharField(choices=[('Rückruf', 'Rückruf'), ('Termin', 'Termin'), ('Wiederanruf', 'Wiederanruf')], default='Rückruf', max_length=20)),
                ('gespraechsinhalt', models.TextField()),
                ('firmen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vermerke', to='kunden.kunde')),
            ],
        ),
    ]
