# Generated by Django 5.1.7 on 2025-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vermerk',
            name='firma',
        ),
        migrations.AddField(
            model_name='vermerk',
            name='aufgenommen',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vermerk',
            name='verfuegung',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='vermerk',
            name='kontaktart',
            field=models.CharField(choices=[('Eingehender Anruf', 'Anruf von'), ('Ausgehender Anruf', 'Anruf bei'), ('Im Büro', 'Besuch von'), ('Beim Kunden', 'Besuch bei')], default='Anruf', max_length=18),
        ),
        migrations.AlterField(
            model_name='vermerk',
            name='wunsch',
            field=models.CharField(choices=[('wünscht Rückruf', 'wünscht Rückruf'), ('wünscht Termin', 'wünscht Termin'), ('ruft wieder zurück', 'ruft wieder an')], default='wünscht Rückruf', max_length=20),
        ),
    ]
