# Generated by Django 5.1.7 on 2025-03-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunden', '0002_remove_vermerk_firma_vermerk_aufgenommen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vermerk',
            name='anschrift',
        ),
        migrations.RemoveField(
            model_name='vermerk',
            name='fax_nr',
        ),
        migrations.RemoveField(
            model_name='vermerk',
            name='telefon_nr',
        ),
    ]
