# Generated by Django 5.1.7 on 2025-03-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunden', '0003_remove_vermerk_anschrift_remove_vermerk_fax_nr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermerk',
            name='uhrzeit',
            field=models.TimeField(),
        ),
    ]
