# Generated by Django 5.1.7 on 2025-03-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunden', '0004_alter_vermerk_uhrzeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='plz',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
